service: todoapi

provider:
  name: aws
  runtime: nodejs4.3
  credentials: ${file(./.env.yml):credentials}

custom:
  writeEnvVars:
    NODE_ENV: ${file(./.env.yml):${opt:stage}.NODE_ENV}
    DATABASE_URL: ${file(./.env.yml):${opt:stage}.DATABASE_URL}
    DEBUG: ${file(./.env.yml):${opt:stage}.DEBUG}

plugins:
  - serverless-plugin-write-env-vars

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
